package com.openlattice.chronicle.timeusediary

/**
 * @author alfoncenzioka &lt;alfonce@openlattice.com&gt;
 */
class TimeUseDiarySummarizedDataVariables {
    companion object {
        const val PRIMARY_BATHROOM_DURATION= "primary_bathroom_mins"
        const val ADULT_MEDIA_BLOCKS =  "adultMedia_blocks"
        const val SLEEP_ARRANGEMENT = "sleepArrangement"
        const val BG_AUDIO_NIGHT = "bgAudioNight"
        const val PRIMARY_CHILDCARE_BLOCKS = "primary_childcare_blocks"
        const val PRIMARY_MEDIA_DURATION = "primary_media_mins"
        const val DAY_TIME_END = "dayEndTime"
        const val PRIMARY_MEDIA_CO_VIEWERS_BLOCKS = "primary_media_coviewers_blocks"
        const val BD_MEDIA_DAY_BLOCKS = "bgMediaDay_blocks"
        const val PRIMARY_CHILDCARE_DURATION = "primary_childcare_mins"
        const val PRIMARY_PLAY_INSIDE_DURATION = "primary_play_inside_mins"
        const val ADULT_MEDIA_DURATION = "adultMedia_mins"
        const val DAY_OF_WEEK = "dayOfWeek"
        const val TYPICAL_SLEEP_PATTERN = "typicalSleepPattern"
        const val WAKE_UP_COUNT = "wakeUpCount"
        const val BG_MEDIA_DAY_DURATION = "bgMediaDay_mins"
        const val SCREEN_ONE_HOUR_FROM_SLEEPING_BLOCKS =  "screen_1hfromsleeping_blocks"
        const val TYPICAL_DAY = "typicalDay"
        const val SECONDARY_BOOK_TITLE = "secondaryBookTitle"
        const val SCREEN_DURATION_PLAYING_PROPORTION = "screen_during_Playing_proportion"
        const val PRIMARY_EATING_DURATION = "primary_eating_mins"
        const val BG_TV_DAY_DURATION = "bgTvDay_mins"
        const val PRIMARY_READING_DURATION = "primary_reading_mins"
        const val PRIMARY_PLAY_INSIDE_BLOCKS =  "primary_play_inside_blocks"
        const val TODAY_WAKE_UP_TIME = "todayWakeUpTime"
        const val PRIMARY_OTHER_AT_HOME_BLOCKS = "primary_other_at_home_blocks"
        const val PRIMARY_MEDIA_BLOCKS = "primary_media_blocks"
        const val PRIMARY_BATHROOM_BLOCKS =  "primary_bathroom_blocks"
        const val SCREEN_DURING_SLEEPING_DURATION = "screen_during_sleeping_proportion"
        const val PRIMARY_OTHER_AT_HOME_DURATION = "primary_other_at_home_mins"
        const val PRIMARY_MEDIA_NAME = "primaryMediaName"
        const val BG_TV_DAY_BLOCKS =  "bgTvDay_blocks"
        const val PRIMARY_MEDIA_CO_VIEWERS_DURATION =  "primary_media_coviewers_mins"
        const val PRIMARY_MEDIA_PLAY_OUTSIDE_DURATION = "primary_play_outside_mins"
        const val DAY_START_TIME =  "dayStartTime"
        const val SCREEN_DURING_EATING_PROPORTION =  "screen_during_Eating_proportion"
        const val BG_AUDIO_DAY_DURATION =  "bgAudioDay_mins"
        const val NON_TYPICAL_DAY_REASON =  "nonTypicalDayReason"
        const val PRIMARY_PLAY_OUTSIDE_BLOCKS = "primary_play_outside_blocks"
        const val BG_TV_NIGHT =  "bgTvNight"
        const val PRIMARY_READING_BLOCKS = "primary_reading_blocks"
        const val BG_AUDIO_DAY_BLOCKS =  "bgAudioDay_blocks"
        const val PRIMARY_EATING_BLOCKS =  "primary_eating_blocks"
        const val PRIMARY_BOOK_TITLE =  "primaryBookTitle"
        const val SECONDARY_MEDIA_NAME =  "secondaryMediaName"
        const val WAVE_ID =  "waveId"
        const val NON_TYPICAL_SLEEP_REASON = "nonTypicalSleepReason"
        const val FAMILY_ID = "familyId"
    }
}
